package lexer

type TokenType int

const (
	TOKEN_ERROR TokenType = iota
	TOKEN_EOF
	TOKEN_IDENT

	TOKEN_END_OF_LINE
	TOKEN_NEWLINE
	TOKEN_WHITESPACE

	TOKEN_LEFT_BRACKET
	TOKEN_RIGHT_BRACKET
	TOKEN_LEFT_CURLY_BRACKET
	TOKEN_RIGHT_CURLY_BRACKET
	TOKEN_LEFT_SQUARE_BRACKET
	TOKEN_RIGHT_SQUARE_BRACKET

	TOKEN_VAR_DECLARATION
	TOKEN_VAR_EQUALS
	TOKEN_CONST

	TOKEN_TYPE_INT
	TOKEN_TYPE_STRING
	TOKEN_TYPE_BOOL
	TOKEN_TYPE_DOUBLE
	TOKEN_TYPE_FLOAT
	TOKEN_TYPE_CHAR

	TOKEN_STR_QUOTE
	TOKEN_CHAR_QUOAT

	TOKEN_PLUS
	TOKEN_MINUS
	TOKEN_DIVIDE
	TOKEN_MOD
	TOKEN_MULTIPLY

	TOKEN_COMMAND_IF
	TOKEN_COMMAND_FOR
	TOKEN_COMMAND_WHILE
	TOKEN_COMMAND_FUNC

	TOKEN_CONDITION_EQUALS
	TOKEN_CONDITION_NOT_EQUAL
	TOKEN_CONDITION_MORE_THAN
	TOKEN_CONDITION_MORE_THAN_EQUAL
	TOKEN_CONDITION_LESS_THAN
	TOKEN_CONDITION_LESS_THAN_EQUAL
)
